using System.Text.RegularExpressions;
using Microsoft.Extensions.Options;

namespace AI.Document.Converter.Persistence.Storage;

public sealed class LocalFileSystemObjectStorageOptions
{
    // Must be outside the application's content root, and therefore outside any
    // static-file webroot (SR-SEC-4). Defaults under the OS temp directory so a
    // developer cannot accidentally serve customer documents by dropping them
    // in wwwroot.
    public string RootDirectory { get; set; } =
        Path.Combine(Path.GetTempPath(), "adc-object-storage");
}

// Local-development adapter for IObjectStorage. Production will use a private
// object store; this exists so the upload and download paths can be built and
// tested without one, and so the interface is proven against a real
// implementation rather than a mock.
public sealed class LocalFileSystemObjectStorage : IObjectStorage
{
    // Keys are generated by StorageKeys, never by user input - but this class
    // is the last line before a path is constructed, so it validates anyway.
    // A component that trusts its caller is a component that stops being safe
    // the moment someone adds a new caller.
    private static readonly Regex SafeKeyPattern =
        new(@"^[a-z0-9]+(/[a-z0-9\-]+)*$", RegexOptions.Compiled);

    private readonly string _rootDirectory;

    public LocalFileSystemObjectStorage(IOptions<LocalFileSystemObjectStorageOptions> options)
    {
        _rootDirectory = Path.GetFullPath(options.Value.RootDirectory);
    }

    public async Task<long> WriteAsync(string key, Stream content, CancellationToken cancellationToken)
    {
        var path = ResolvePath(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        // Write to a temporary name and move into place. A crash mid-write must
        // not leave a truncated object that later looks like a complete one -
        // SR-JOB-3's "incomplete artifacts are never downloadable" only holds if
        // publication is atomic.
        var temporaryPath = path + ".partial";

        long written;
        await using (var destination = new FileStream(
            temporaryPath, FileMode.Create, FileAccess.Write, FileShare.None))
        {
            await content.CopyToAsync(destination, cancellationToken);
            written = destination.Length;
        }

        File.Move(temporaryPath, path, overwrite: true);
        return written;
    }

    public Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken)
    {
        var path = ResolvePath(key);

        if (!File.Exists(path))
        {
            return Task.FromResult<Stream?>(null);
        }

        Stream stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
        return Task.FromResult<Stream?>(stream);
    }

    public Task<bool> ExistsAsync(string key, CancellationToken cancellationToken) =>
        Task.FromResult(File.Exists(ResolvePath(key)));

    public Task DeleteAsync(string key, CancellationToken cancellationToken)
    {
        var path = ResolvePath(key);

        // Idempotent by design: a retention sweep and a customer deletion may
        // both target the same object, and neither should fail because the
        // other got there first.
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    public async IAsyncEnumerable<StoredObject> ListAsync(
        string prefix,
        [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var root = string.IsNullOrEmpty(prefix) ? _rootDirectory : ResolvePath(prefix);

        if (!Directory.Exists(root))
        {
            yield break;
        }

        foreach (var path in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
        {
            cancellationToken.ThrowIfCancellationRequested();

            // A ".partial" file is a write in progress (see WriteAsync). It has
            // no key and no row, and treating it as an orphan would delete
            // somebody's upload mid-flight.
            if (path.EndsWith(".partial", StringComparison.Ordinal))
            {
                continue;
            }

            var info = new FileInfo(path);
            var key = Path.GetRelativePath(_rootDirectory, path).Replace(Path.DirectorySeparatorChar, '/');

            yield return new StoredObject(key, info.Length, info.LastWriteTimeUtc);
        }

        await Task.CompletedTask;
    }

    private string ResolvePath(string key)
    {
        if (string.IsNullOrWhiteSpace(key) || !SafeKeyPattern.IsMatch(key))
        {
            throw new ArgumentException(
                "Storage key is not in the expected form. Keys are generated by StorageKeys and "
                + "must never be built from user input.",
                nameof(key));
        }

        var combined = Path.GetFullPath(Path.Combine(_rootDirectory, key));

        // Belt and braces. The pattern above already forbids "..", but the
        // consequence of being wrong here is reading or overwriting an
        // arbitrary file, so the resolved path is checked to actually be inside
        // the root rather than assumed to be.
        if (!combined.StartsWith(_rootDirectory + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && combined != _rootDirectory)
        {
            throw new ArgumentException("Storage key resolved outside the storage root.", nameof(key));
        }

        return combined;
    }
}
